---
title: "A worked example"
author: "Andrew L Jackson"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{A worked example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteDepends{lamW}
  %\VignetteDepends{tidyverse}
  %\VignetteDepends{patchwork}
  \usepackage[utf8]{inputenc}
---


## Setup

```{r}
library(predictFishRMR)

# for plotting and tibble manipulation
library(tidyverse)


```

## Introduction

Here we use the functions in the pacakge `predictFishRMR` to predict various features of a fishe's metabolism and ecological constraints based on their mass and physiology type. 

For this example we pick a fish with mass = 3000g.

```{r}

# mass of fish
mm <- 1000

# range of water temperatures in C
Ta <- seq(0,30, by = 0.25)

# mesotherm (meso = T) or ecotherm (meso = F)?
mesotherm <- TRUE

# Estimate the cooling coefficient K
K <- kfun(m = mm)

# load the fitted regression model and extract the parameters
data("fittedModelRMR")
pars <- fittedModelRMR$fixef[,1]

# loop over the sequence of water temperatures in the vector Ta
# Estimate the body temperature at thermal equilibrium and take only the 
# first branch of the Lambert function estimates. 
Tm <- Ta |>
  map(\(x) bodyTempLambert(x, m = mm, k = K, meso = mesotherm, pars = pars)) |>
  bind_rows() |>
  filter(branch == 0)

# Estimate routine metabolic rate RMR over the range of  body temperatures
RMR <- RMRfun(mm, Tm$y, mesotherm, pars = pars)


# create a tibble for plotting in ggplot
dd <- tibble(Ta = Ta, Tm = Tm, RMR = RMR)

```

Plot the relationship between RMR and Ta

```{r}

g1 <- ggplot(data = dd, mapping = aes(x = Ta, y = Tm$y)) + 
  geom_line() + 
  ggtitle(paste0("mass = ", mm, "kg"))

print(g1)

```





